export type ShopifyItemRow = {
  Handle: string;
  Title: string;
  'Body (HTML)': string;
  Vendor: string;
  'Product Category': string;
  Type: string;
  Tags: string;
  Published: boolean;
  'Option1 Name': string;
  'Option1 Value': string;
  'Option1 Linked To': string;
  'Option2 Name': string;
  'Option2 Value': string;
  'Option2 Linked To': string;
  'Option3 Name': string;
  'Option3 Value': string;
  'Option3 Linked To': string;
  'Variant SKU': string;
  'Variant Grams': number;
  'Variant Inventory Tracker': string;
  'Variant Inventory Qty': number;
  'Variant Inventory Policy': string;
  'Variant Fulfillment Service': string;
  'Variant Price': number;
  'Variant Compare At Price': number;
  'Variant Requires Shipping': boolean;
  'Variant Taxable': boolean;
  'Unit Price Total Measure': number;
  'Unit Price Total Measure Unit': string;
  'Unit Price Base Measure': number;
  'Unit Price Base Measure Unit': string;
  'Variant Barcode': string;
  'Image Src': string;
  'Image Position': number;
  'Image Alt Text': string;
  'Gift Card': boolean;
  'SEO Title': string;
  'SEO Description': string;
  'Cases Available (product.metafields.tres_noir.cases_available)': number;
  'Default Case Type (product.metafields.tres_noir.default_case_type)': string;
  'Fit Dimensions (product.metafields.tres_noir.fit_dimensions)': string;
  'Fit Type (product.metafields.tres_noir.fit_type)': string;
  'Frame Width (product.metafields.tres_noir.frame_width)': number;
  'Frame Width Measurement (product.metafields.tres_noir.frame_width_measurement)': string;
  'RX-Able (product.metafields.tres_noir.rx_able)': boolean;
  'Style Description (product.metafields.tres_noir.style_description)': string;
  'Custom Title (product.metafields.tres_noir.title)': string;
  'Variant Image': string;
  'Variant Weight Unit': string;
  'Variant Tax Code': string;
  'Cost per item': number;
  Status: string;
};
